name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  androidBuild:
    defaults:
      run:
        working-directory: ./src/android

    name: Build android app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
      - name: Assemble app debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload app APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: src/android/RHVoice-core/build/outputs/apk/debug/RHVoice-core-debug.apk

  windowsBuild:
    name: Build windows packages
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: python -m pip install --upgrade pip lxml scons
      - name: build
        run: scons -j2

      - name: Upload packages archive
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: build/windows/packages
